apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "college-media.fullname" . }}-backend
  labels:
    {{- include "college-media.labels" . | nindent 4 }}
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "college-media.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      labels:
        {{- include "college-media.selectorLabels" . | nindent 8 }}
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: MONGO_URI
              value: {{ .Values.backend.env.mongoUri | quote }}
            - name: REDIS_URL
              value: {{ .Values.backend.env.redisUrl | quote }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
